### ISSUE TITLE
Is the port changable?

### ISSUE THREAD

**Issue by Stexxen** [gocardless/cli-releases#11]
I have other services running on port 8080, so when I attempt to use `gc` I get the following

```
% gc login
2022/05/09 12:07:10 Error: could not create oauth redirect listener, check port is available: listen tcp :8080: bind: address already in use
```

The docs show no way to change this. Is is possible or hardcoded?

**Comment by perfectmak** [comment]
Hi @Stexxen, There is currently no way to change this port number since that port is setup on the CLI GC's App as it's callback url.

For now, you'll have to leave your port 8080 open.
